stages: 
  - build
  - deploy
  
build: 
  stage: build
  script: 
    - mvn --version
    - mvn clean install -Dmaven.test.skip=true
    - java -jar helloworld-0.0.1-SNAPSHOT.jar
    - whoami
    - cd ~
    - ls -la

  artifacts:
    paths:
      - target/*.jar
  only:
    - master
  tags:
    - gitlabrunner-aws


    
